export const COLORS = {
    theme : '#FFFFFF',
    button: '#1F9CEF',
    introText: '#0F141A',
    loginTextInput : '#222B2E',
    loginText: '#11203D',
    registerTextInput : '#222B2E',
    textInputBorder: '#546471',
    label: '#222B2E',
    white: '#FFFFFF',
    lightgray: '#eee',
    cream : '#FEF5E7',
    black: '#000',
    green: '#229954',
    yellow:'yellow',
    orange:'orange',
    red : 'red',
    blue: '#1F9CEF',
}